### ISSUE TITLE
CSS loading issue?

### ISSUE THREAD

**Issue by michaltakac** [e2b-dev/ai-artifacts#1]
This is how the app looks like when I open it in Safar/Chrome/Firefox:

<img width="690" alt="Screenshot 2024-07-17 at 12 06 37" src="https://github.com/user-attachments/assets/aac0b586-5ce0-4ecf-be13-bdf33b80fcae">

Seems like it is not loading Tailwind properly.

**Comment by mlejva** [comment]
Do you have any terminal output or errors? Because I can't reproduce it

**Comment by michaltakac** [comment]
No, all is running properly. Maybe some local network issue on my side or something then... investigating.

**Comment by michaltakac** [comment]
Yes, installing it with `pnpm i` was the issue. `npm i` works with turbopack.

<img width="1800" alt="Screenshot 2024-07-17 at 15 34 02" src="https://github.com/user-attachments/assets/57675e50-ce51-4457-92c8-0c4a1f3ddca9">
