### ISSUE TITLE
supabaseUrl is required.

### ISSUE THREAD

**Issue by pzc163** [e2b-dev/ai-artifacts#13]
when run  npm run dev ,there is an error Error: supabaseUrl is required.
where can get supabaseUrl?
![image](https://github.com/user-attachments/assets/f5763d7c-d979-4ec0-99b5-d19ea310eddf)

**Comment by heartsinaustin** [comment]
I am getting the same thing.  I actually tried on my local machine and then tried from a virtual machine with windows and both had the same error.  One suggestion was to see if I had anything running on port 3000 when launching the program.  I checked netstat and didnt see anything running.

**Comment by WizKid1968** [comment]
I'm having the same issue. I was using port 3000 to run another app that required supabase (I'm not sure that would be the issue), however, I quit that app and I'm still having the same issue.

**Comment by WizKid1968** [comment]
> when run npm run dev ,there is an error Error: supabaseUrl is required. where can get supabaseUrl? ![image](https://private-user-images.githubusercontent.com/105222039/356800255-f5763d7c-d979-4ec0-99b5-d19ea310eddf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzODExMTIsIm5iZiI6MTcyMzM4MDgxMiwicGF0aCI6Ii8xMDUyMjIwMzkvMzU2ODAwMjU1LWY1NzYzZDdjLWQ5NzktNGVjMC05OWI1LWQxOWVhMzEwZWRkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQxMjUzMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZmNlMWQ1NTYzYTg5OGFjM2MyMmEwMzE3MDY4ZmU0YzUxMjFlZjhmNmQyOTIxNTg0MjBhZmZkYWU1ODZkYmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bn5wwrB1gTz86yJl4nu2rL4zCpDYIND_fRmkChPk3Wk)

Supabase is part of the new update Supabase is required. 
Create a Supabase project then copy and paste the supabase url & your anon key to your .env.local: 
NEXT_PUBLIC_SUPABASE_URL="your-supabaseurl"
NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key

**Comment by mishushakov** [comment]
Have fixed this in #21
