### ISSUE TITLE
Password in demosite

### ISSUE THREAD

**Issue by sid-newby** [e2b-dev/ai-artifacts#19]
I already have an account with e2b but I never set a password, instead I authenticate with github. The github login is broken on the demosite. So I login to edb and try to reset my password. Email link is sent, but it just takes me to the front page. No password reset. 

All of your demos are broken. the code snippets are incomplete and require much more than whats provided. It's clear that you guys wanna sell hosted services and the open source offering is just a fucking sales trap.

**Comment by mishushakov** [comment]
Hey, are you running it yourself on localhost or using the hosted app (artifacts.e2b.dev)?
There's an issue around resetting passwords (#22) and we're actively working on a fix.

Can you also provide me some more context regarding broken demos and code snippets you're referring to?

I understand your concerns, but want to clarify that it is our priority to make the app work locally without the dependence on any cloud offerings 🙏

**Comment by mishushakov** [comment]
Closing, because there are no actionable items on this issue, besides what I already mentioned.
