### ISSUE TITLE
Add Agentic Modularity

### ISSUE THREAD

**Issue by rkeshwani** [e2b-dev/ai-artifacts#2]
As a user I want to be able to run different agents in the left half of the screen and view their outputs in the right half.
A good example of this is Perplexity's pro search that performs searches and displays what's doing in a nice ui.

So if web search was performed, the right half could display the results.
If a recipe search was performed, the right half displays the collection of recipes.
If stock data was retrieved, the right half displays the data that was retrieved.
Could create a separate agent store from this idea and you select the agents you want.

The results on the left update showing which agent is being used and clicked on that shows the right half and that agent's results.

**Comment by mishushakov** [comment]
Hey, thanks for the feedback!
Sounds like an interesting idea but it's a bit out-of-scope for this project, we're currently more focused on solving reliability 😄
