### ISSUE TITLE
getting error while using Gemini model 

### ISSUE THREAD

**Issue by sallumandya1995** [e2b-dev/ai-artifacts#34]
model {
  id: 'models/gemini-1.5-pro-latest',
  provider: 'Google AI',
  providerId: 'google',
  name: 'Gemini Pro',
  hosted: true
}
config {
  model: 'models/gemini-1.5-pro-latest',
  apiKey: 's'ssas
}
The data stream is hanging. Did you forget to close it with `data.close()`?
 POST /api/chat 200 in 17333ms
{ messages: [], data: undefined }
 GET / 200 in 359ms
 GET /favicon.ico 200 in 223ms

**Comment by mishushakov** [comment]
This should be resolved now. Can you try again and let me know if you're still experiencing any issues?

**Comment by mishushakov** [comment]
Make sure you're always using the latest version of the repository 👍
