### ISSUE TITLE
Auto Artifacts generation

### ISSUE THREAD

**Issue by Huybp08082016** [e2b-dev/ai-artifacts#40]
Hello, this is Gia Huy here, an avid user of this AI Project. I've been using this for weeks, but suddenly today you started to change something. Whenever I says hello, previously it did give me a greeting without generation, but today, I don't like to generate, instead it said "Generating artifact...". Can you fix this problem? Sometimes I need to get away from it for a while to use for creative writing stuffs... Please fix it for me

**Comment by mishushakov** [comment]
We are focused on generating runnable artifacts currently, there's no plan for supporting general chats.
