### ISSUE TITLE
unhandled runtime error

### ISSUE THREAD

**Issue by justinzw** [e2b-dev/ai-artifacts#41]
I ran the application locally and tried a few simple prompts. 

The code looks like it generated fine but the preview does not work. 

I get this error:

![image](https://github.com/user-attachments/assets/b168aaea-39b1-4f1e-92d6-14ff08ad3438)

**Comment by mishushakov** [comment]
Give me some more context:

- Which model?
- Sample code?
- Have you set your API Keys in the `E2B_API_KEY` env variable?
