### ISSUE TITLE
local setup

### ISSUE THREAD

**Issue by volkancirik** [e2b-dev/ai-artifacts#46]
Hello,

is it possible to run `E2B` locally and use that sandbox without using the`E2B_API_KEY`?

**Comment by mishushakov** [comment]
You should see https://github.com/e2b-dev/infra for running E2B locally, you will need to set some additional variables though:

https://github.com/e2b-dev/E2B/blob/833e78726ac4c31b87776672f1f1cd40287804ab/packages/js-sdk/src/constants.ts#L5-L7

**Comment by sammcj** [comment]
I came to ask the same thing, looking at e2b's infra - it's pretty tightly coupled to running on GCP?

**Comment by volkancirik** [comment]
thanks!

**Comment by mlejva** [comment]
Hey @sammcj, yes for now. We're working on adding support for AWS as well and then any Linux machine
