### ISSUE TITLE
Local LLM Ollama:llama3.1

### ISSUE THREAD

**Issue by trasgoverde** [e2b-dev/ai-artifacts#47]
### **  Artifacts with Local Models**
*** Not artifacts are shown as with other models, When trying with my setup locally Ollama models do not show any Artifacts in the side. 
* The artifacts are shown with Antrophic, Gpt-4, I did not tried with other models.** 

** env file with correct api keys for all **

**Comment by mishushakov** [comment]
I had some success with it today, but you have to make sure the prompt is very explicit:

<img width="1912" alt="Screenshot 2024-08-30 at 11 42 46" src="https://github.com/user-attachments/assets/aa7ee7b6-ad0c-4ec0-a640-0d6636e3dff0">

**Comment by mishushakov** [comment]
could also pull off a very basic todo app

<img width="1920" alt="Screenshot 2024-08-30 at 11 49 01" src="https://github.com/user-attachments/assets/286bfceb-0ade-448b-8c40-97df062f0431">

**Comment by trasgoverde** [comment]
Thank you, I am gonna test it.

Best,
