### ISSUE TITLE
interactive input 

### ISSUE THREAD

**Issue by Garin2-colab** [e2b-dev/ai-artifacts#5]
Hi when I tried your "create minimalistic Todo app' I got this error for previewing the result. It seems like the environment couldn't have interactive input. However your example has a nice output. How can I 'upgrade' my environment?

StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

![image](https://github.com/user-attachments/assets/f848501a-cccb-45f6-8f44-5d53d518808a)

**Comment by mishushakov** [comment]
I believe there was a bug with the application a while ago.
Could you pull the latest version of the repo and try running it again?

Feel free to reopen if you experience any issues.

**Comment by Garin2-colab** [comment]
ok i'll try it again!. thank you for the reply
